import jsPDF from "jspdf";
import { GeneratedReport, SOURCE_COLORS } from "@/types/report";

const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const MARGIN_TOP = 40;
const MARGIN_BOTTOM = 30;
const LINE_HEIGHT = 5.5;
const FONT_SIZE = 9.5;

const BRAND_GREEN: [number, number, number] = [16, 185, 129];
const BRAND_DARK: [number, number, number] = [15, 23, 42];

// Turnitin-style source badge colors
const TURNITIN_PDF_COLORS: [number, number, number][] = [
  [220, 38, 38],   // red
  [234, 88, 12],   // orange
  [202, 138, 4],   // amber
  [22, 163, 74],   // green
  [13, 148, 136],  // teal
  [37, 99, 235],   // blue
  [79, 70, 229],   // indigo
  [147, 51, 234],  // purple
  [219, 39, 119],  // pink
  [225, 29, 72],   // rose
];

let logoDataUrl: string | null = null;

async function loadLogo(): Promise<string> {
  if (logoDataUrl) return logoDataUrl;
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0);
      logoDataUrl = canvas.toDataURL("image/png");
      resolve(logoDataUrl);
    };
    img.onerror = () => resolve("");
    img.src = "/shantrix-logo.png";
  });
}

function addHeader(doc: jsPDF, logo: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, pageWidth, 3, "F");

  if (logo) {
    try { doc.addImage(logo, "PNG", MARGIN_LEFT, 5, 12, 12); } catch {}
  }

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_GREEN);
  doc.text("Shantrix", MARGIN_LEFT + 14, 12);

  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("AI-Powered Academic Integrity Platform", MARGIN_LEFT + 14, 16);

  const pageNum = (doc as any).internal.getCurrentPageInfo().pageNumber;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum}`, pageWidth - MARGIN_RIGHT, 12, { align: "right" });

  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, 20, pageWidth - MARGIN_RIGHT, 20);
}

function addFooter(doc: jsPDF) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by Shantrix · ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 10, { align: "center" });
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.5);
  doc.line(0, pageHeight - 4, pageWidth, pageHeight - 4);
}

function ensureSpace(doc: jsPDF, y: number, needed: number, logo: string): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - MARGIN_BOTTOM) {
    addFooter(doc);
    doc.addPage();
    addHeader(doc, logo);
    return MARGIN_TOP;
  }
  return y;
}

function buildHighlightMap(report: GeneratedReport): Map<number, { type: "plagiarism" | "ai_generated"; sourceTitle: string; similarity: number; sourceIdx: number }> {
  const map = new Map();
  const sourceIdxMap = new Map<string, number>();
  report.sources.forEach((s, i) => sourceIdxMap.set(s.id, i));

  for (const span of report.matchSpans) {
    const sourceIdx = sourceIdxMap.get(span.sourceId) ?? 0;
    for (let i = span.startOffset; i < span.endOffset; i++) {
      map.set(i, { type: span.matchType, sourceTitle: span.sourceTitle, similarity: span.similarityScoreForSpan, sourceIdx });
    }
  }
  return map;
}

export async function exportReportPDF(report: GeneratedReport) {
  const logo = await loadLogo();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;

  // ═══════ COVER PAGE ═══════
  addHeader(doc, logo);
  let y = MARGIN_TOP;

  // Title & author
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(report.title, MARGIN_LEFT, y);
  y += 10;

  // Turnitin-style "ORIGINALITY REPORT" header
  doc.setDrawColor(200, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 0, 0);
  doc.text("ORIGINALITY REPORT", MARGIN_LEFT, y);
  y += 6;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 8;

  // Score boxes - Turnitin style (4 columns)
  const colW = contentWidth / 4;
  const webSrcCount = report.sources.filter(s => s.type === 'web').length;
  const pubSrcCount = report.sources.filter(s => ['journal', 'publication'].includes(s.type)).length;
  const studentSrcCount = report.sources.filter(s => ['student', 'repository'].includes(s.type)).length;

  const scores = [
    { value: `${report.similarityScore}%`, label: "SIMILARITY INDEX", color: [200, 0, 0] as [number, number, number] },
    { value: `${webSrcCount}%`, label: "INTERNET SOURCES", color: [80, 80, 80] as [number, number, number] },
    { value: `${pubSrcCount}%`, label: "PUBLICATIONS", color: [80, 80, 80] as [number, number, number] },
    { value: `${studentSrcCount}%`, label: "STUDENT PAPERS", color: [80, 80, 80] as [number, number, number] },
  ];

  for (let i = 0; i < scores.length; i++) {
    const x = MARGIN_LEFT + i * colW;
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...scores[i].color);
    doc.text(scores[i].value, x, y + 5);
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(scores[i].label, x, y + 10);
  }
  y += 18;

  // AI score
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text(`AI CONTENT: ${report.aiScore}%`, MARGIN_LEFT, y);
  y += 8;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 8;

  // PRIMARY SOURCES list - Turnitin style
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 0, 0);
  doc.text("PRIMARY SOURCES", MARGIN_LEFT, y);
  y += 6;

  for (let si = 0; si < report.sources.length; si++) {
    const src = report.sources[si];
    y = ensureSpace(doc, y, 16, logo);

    const tc = TURNITIN_PDF_COLORS[si % TURNITIN_PDF_COLORS.length];

    // Colored number badge
    doc.setFillColor(...tc);
    doc.roundedRect(MARGIN_LEFT, y - 4, 8, 8, 1, 1, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`${si + 1}`, MARGIN_LEFT + 4, y + 1, { align: "center" });

    // Source title
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...tc);
    doc.text(src.title.substring(0, 60), MARGIN_LEFT + 12, y);

    // Source type
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    const typeLabel = src.type === 'web' ? 'Internet Source' : src.type === 'journal' ? 'Journal' : src.type === 'publication' ? 'Publication' : src.type === 'student' ? 'Student Paper' : 'Repository';
    doc.text(typeLabel, MARGIN_LEFT + 12, y + 4);

    // Percentage on right
    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    const pctText = src.percentContribution < 1 ? '<1%' : `${src.percentContribution}%`;
    doc.text(pctText, pageWidth - MARGIN_RIGHT, y, { align: "right" });

    y += 12;
    doc.setDrawColor(230, 230, 230);
    doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
    y += 4;
  }

  // Metadata
  y = ensureSpace(doc, y, 20, logo);
  y += 4;
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Submission date: ${new Date(report.submissionDate).toLocaleString()}`, MARGIN_LEFT, y); y += 4;
  doc.text(`Submission ID: ${report.submissionId}`, MARGIN_LEFT, y); y += 4;
  doc.text(`File name: ${report.fileName || report.title}`, MARGIN_LEFT, y); y += 4;
  doc.text(`Word count: ${report.wordCount}  ·  Character count: ${report.charCount}`, MARGIN_LEFT, y); y += 4;

  // Exclusion settings
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 5;
  doc.setFontSize(7);
  doc.text("Exclude quotes: On          Exclude matches: Off", MARGIN_LEFT, y); y += 4;
  doc.text("Exclude bibliography: On", MARGIN_LEFT, y);

  // ═══════ DOCUMENT WITH HIGHLIGHTS ═══════
  addFooter(doc);
  doc.addPage();
  addHeader(doc, logo);
  y = MARGIN_TOP;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Document Analysis", MARGIN_LEFT, y);
  y += 4;

  // Legend
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.setFillColor(254, 240, 138);
  doc.rect(MARGIN_LEFT, y, 12, 3.5, "F");
  doc.text("= Plagiarism", MARGIN_LEFT + 14, y + 3);
  doc.setFillColor(191, 219, 254);
  doc.rect(MARGIN_LEFT + 50, y, 12, 3.5, "F");
  doc.text("= AI Content", MARGIN_LEFT + 64, y + 3);
  y += 8;

  const highlightMap = buildHighlightMap(report);
  const lines = report.content.split("\n");

  doc.setFontSize(FONT_SIZE);
  let globalCharOffset = 0;

  for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
    const line = lines[lineIdx];
    if (line.trim() === "") {
      globalCharOffset += line.length + 1;
      y += 2.5;
      continue;
    }

    doc.setFont("helvetica", "normal");
    const wrappedLines = doc.splitTextToSize(line, contentWidth - 8);

    let lineCharCursor = globalCharOffset;

    for (const wLine of wrappedLines) {
      y = ensureSpace(doc, y, LINE_HEIGHT + 2, logo);
      const segStart = lineCharCursor;
      const segEnd = lineCharCursor + wLine.length;

      let hasPlag = false;
      let hasAI = false;
      let matchLabel = "";
      let sourceIdx = -1;

      for (let ci = segStart; ci < segEnd && ci < report.content.length; ci++) {
        const h = highlightMap.get(ci);
        if (h) {
          if (h.type === "plagiarism") {
            hasPlag = true;
            if (sourceIdx < 0) {
              sourceIdx = h.sourceIdx;
              matchLabel = `[${h.sourceIdx + 1}]`;
            }
          }
          if (h.type === "ai_generated") hasAI = true;
        }
      }

      const textW = doc.getTextWidth(wLine);
      if (hasPlag) {
        doc.setFillColor(254, 240, 138);
        doc.rect(MARGIN_LEFT, y - 3.5, Math.min(textW + 3, contentWidth), LINE_HEIGHT, "F");
      } else if (hasAI) {
        doc.setFillColor(191, 219, 254);
        doc.rect(MARGIN_LEFT, y - 3.5, Math.min(textW + 3, contentWidth), LINE_HEIGHT, "F");
      }

      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", hasPlag || hasAI ? "bold" : "normal");
      doc.text(wLine, MARGIN_LEFT + 1, y);

      // Add Turnitin-style source number badge
      if (hasPlag && sourceIdx >= 0) {
        const badgeX = Math.min(MARGIN_LEFT + textW + 3, pageWidth - MARGIN_RIGHT - 8);
        const tc = TURNITIN_PDF_COLORS[sourceIdx % TURNITIN_PDF_COLORS.length];
        doc.setFillColor(...tc);
        doc.roundedRect(badgeX, y - 3.5, 5, 4.5, 0.5, 0.5, "F");
        doc.setFontSize(5.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(`${sourceIdx + 1}`, badgeX + 2.5, y, { align: "center" });
        doc.setFontSize(FONT_SIZE);
      }

      y += LINE_HEIGHT;
      lineCharCursor = segEnd;
    }

    globalCharOffset += line.length + 1;
  }

  // ═══════ SOURCES APPENDIX ═══════
  addFooter(doc);
  doc.addPage();
  addHeader(doc, logo);
  y = MARGIN_TOP;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Sources", MARGIN_LEFT, y);
  y += 8;

  for (let si = 0; si < report.sources.length; si++) {
    const src = report.sources[si];
    y = ensureSpace(doc, y, 18, logo);

    const tc = TURNITIN_PDF_COLORS[si % TURNITIN_PDF_COLORS.length];

    // Colored badge
    doc.setFillColor(...tc);
    doc.roundedRect(MARGIN_LEFT, y - 3, 7, 7, 1, 1, "F");
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`${si + 1}`, MARGIN_LEFT + 3.5, y + 1, { align: "center" });

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...tc);
    doc.text(src.title.substring(0, 70), MARGIN_LEFT + 10, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    const typeLabel = src.type === 'web' ? 'Internet Source' : src.type === 'journal' ? 'Journal' : src.type === 'publication' ? 'Publication' : src.type === 'student' ? 'Student Paper' : 'Repository';
    doc.text(`${typeLabel} · Contribution: ${src.percentContribution}% · Words: ${src.matchedWords} · Matches: ${src.occurrences}`, MARGIN_LEFT + 10, y + 5);

    if (src.url) {
      doc.setTextColor(37, 99, 235);
      doc.text(src.url.substring(0, 85), MARGIN_LEFT + 10, y + 9);
    }
    y += 16;
  }

  if (report.sources.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text("No external sources were matched.", MARGIN_LEFT, y);
    y += 8;
  }

  // Summary line
  y = ensureSpace(doc, y, 20, logo);
  y += 5;
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN_LEFT, y, pageWidth - MARGIN_RIGHT, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text(`Total Sources: ${report.totalSources}`, MARGIN_LEFT, y);
  doc.text(`Total Matches: ${report.totalMatches}`, MARGIN_LEFT + 50, y);
  doc.text(`Similarity: ${report.similarityScore}%`, MARGIN_LEFT + 100, y);

  addFooter(doc);

  const fileName = `shantrix-report-${report.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(fileName);
}
