import { PDFDocument, rgb, StandardFonts, PDFPage, PDFFont } from "pdf-lib";
import { GeneratedReport, SOURCE_COLORS } from "@/types/report";
import { supabase } from "@/integrations/supabase/client";

const BRAND_GREEN = rgb(16 / 255, 185 / 255, 129 / 255);
const BRAND_DARK = rgb(15 / 255, 23 / 255, 42 / 255);
const WHITE = rgb(1, 1, 1);
const LIGHT_GRAY = rgb(0.85, 0.85, 0.85);
const MEDIUM_GRAY = rgb(0.5, 0.5, 0.5);
const PLAG_HIGHLIGHT = rgb(254 / 255, 240 / 255, 138 / 255);
const AI_HIGHLIGHT = rgb(191 / 255, 219 / 255, 254 / 255);
const RED = rgb(200 / 255, 0, 0);

const TURNITIN_PDF_COLORS = [
  rgb(220 / 255, 38 / 255, 38 / 255),
  rgb(234 / 255, 88 / 255, 12 / 255),
  rgb(202 / 255, 138 / 255, 4 / 255),
  rgb(22 / 255, 163 / 255, 74 / 255),
  rgb(13 / 255, 148 / 255, 136 / 255),
  rgb(37 / 255, 99 / 255, 235 / 255),
  rgb(79 / 255, 70 / 255, 229 / 255),
  rgb(147 / 255, 51 / 255, 234 / 255),
  rgb(219 / 255, 39 / 255, 119 / 255),
  rgb(225 / 255, 29 / 255, 72 / 255),
];

const MARGIN = 50;
const FONT_SIZE = 9;
const LINE_HEIGHT = 14;

async function loadLogoBytes(): Promise<Uint8Array | null> {
  try {
    const response = await fetch("/shantrix-logo.png");
    if (!response.ok) return null;
    const buffer = await response.arrayBuffer();
    return new Uint8Array(buffer);
  } catch {
    return null;
  }
}

function addBrandHeader(page: PDFPage, font: PDFFont, boldFont: PDFFont, pageNum: number, logoImage: any | null, pdfDoc: PDFDocument) {
  const { width, height } = page.getSize();

  // Green top bar
  page.drawRectangle({ x: 0, y: height - 8, width, height: 8, color: BRAND_GREEN });

  // Logo
  if (logoImage) {
    try {
      page.drawImage(logoImage, { x: MARGIN, y: height - 38, width: 22, height: 22 });
    } catch {}
  }

  // Brand text
  page.drawText("Shantrix", { x: MARGIN + 26, y: height - 28, size: 14, font: boldFont, color: BRAND_GREEN });
  page.drawText("AI-Powered Academic Integrity Platform", { x: MARGIN + 26, y: height - 38, size: 6.5, font, color: MEDIUM_GRAY });

  // Page number
  page.drawText(`Page ${pageNum}`, { x: width - MARGIN - 30, y: height - 28, size: 7, font, color: MEDIUM_GRAY });

  // Divider
  page.drawLine({ start: { x: MARGIN, y: height - 44 }, end: { x: width - MARGIN, y: height - 44 }, thickness: 0.5, color: LIGHT_GRAY });
}

function addBrandFooter(page: PDFPage, font: PDFFont) {
  const { width } = page.getSize();
  page.drawText(`Generated by Shantrix · ${new Date().toLocaleString()}`, { x: width / 2 - 80, y: 16, size: 6, font, color: MEDIUM_GRAY });
  page.drawLine({ start: { x: 0, y: 10 }, end: { x: width, y: 10 }, thickness: 1, color: BRAND_GREEN });
}

function buildHighlightMap(report: GeneratedReport): Map<number, { type: "plagiarism" | "ai_generated"; sourceIdx: number }> {
  const map = new Map();
  const sourceIdxMap = new Map<string, number>();
  report.sources.forEach((s, i) => sourceIdxMap.set(s.id, i));
  for (const span of report.matchSpans) {
    const sourceIdx = sourceIdxMap.get(span.sourceId) ?? 0;
    for (let i = span.startOffset; i < span.endOffset; i++) {
      map.set(i, { type: span.matchType, sourceIdx });
    }
  }
  return map;
}

/**
 * Attempts to download original PDF from storage and merge with report pages.
 * Falls back to text-based rendering if original is not a PDF.
 */
async function tryGetOriginalPDF(report: GeneratedReport): Promise<Uint8Array | null> {
  try {
    // Get submission to find file_url
    const { data: submission } = await supabase
      .from('submissions')
      .select('file_url, file_name')
      .eq('id', report.submissionId)
      .single();

    if (!submission?.file_url || !submission.file_name?.toLowerCase().endsWith('.pdf')) return null;

    const filePath = submission.file_url.split('/submissions/')[1];
    if (!filePath) return null;

    const { data: fileData, error } = await supabase.storage
      .from('submissions')
      .download(decodeURIComponent(filePath));
    if (error || !fileData) return null;

    return new Uint8Array(await fileData.arrayBuffer());
  } catch {
    return null;
  }
}

export async function exportReportPDF(report: GeneratedReport) {
  const logoBytes = await loadLogoBytes();

  // Create the report document
  const reportDoc = await PDFDocument.create();
  const font = await reportDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await reportDoc.embedFont(StandardFonts.HelveticaBold);

  let logoImage: any = null;
  if (logoBytes) {
    try { logoImage = await reportDoc.embedPng(logoBytes); } catch {}
  }

  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const contentWidth = pageWidth - MARGIN * 2;

  // ═══════ COVER PAGE ═══════
  const cover = reportDoc.addPage([pageWidth, pageHeight]);
  addBrandHeader(cover, font, boldFont, 1, logoImage, reportDoc);
  let y = pageHeight - 65;

  // Title
  cover.drawText(report.title, { x: MARGIN, y, size: 12, font, color: MEDIUM_GRAY });
  y -= 16;

  // Red originality report line
  cover.drawLine({ start: { x: MARGIN, y }, end: { x: pageWidth - MARGIN, y }, thickness: 1, color: RED });
  y -= 12;
  cover.drawText("ORIGINALITY REPORT", { x: MARGIN, y, size: 9, font: boldFont, color: RED });
  y -= 8;
  cover.drawLine({ start: { x: MARGIN, y }, end: { x: pageWidth - MARGIN, y }, thickness: 0.3, color: LIGHT_GRAY });
  y -= 20;

  // Score boxes
  const colW = contentWidth / 4;
  const webSrcCount = report.sources.filter(s => s.type === 'web').length;
  const pubSrcCount = report.sources.filter(s => ['journal', 'publication'].includes(s.type)).length;
  const studentSrcCount = report.sources.filter(s => ['student', 'repository'].includes(s.type)).length;

  const scores = [
    { value: `${report.similarityScore}%`, label: "SIMILARITY INDEX", color: RED },
    { value: `${webSrcCount}%`, label: "INTERNET SOURCES", color: MEDIUM_GRAY },
    { value: `${pubSrcCount}%`, label: "PUBLICATIONS", color: MEDIUM_GRAY },
    { value: `${studentSrcCount}%`, label: "STUDENT PAPERS", color: MEDIUM_GRAY },
  ];

  for (let i = 0; i < scores.length; i++) {
    const x = MARGIN + i * colW;
    cover.drawText(scores[i].value, { x, y, size: 24, font: boldFont, color: scores[i].color });
    cover.drawText(scores[i].label, { x, y: y - 14, size: 6, font, color: MEDIUM_GRAY });
  }
  y -= 30;

  // AI score
  cover.drawLine({ start: { x: MARGIN, y }, end: { x: pageWidth - MARGIN, y }, thickness: 0.3, color: LIGHT_GRAY });
  y -= 12;
  cover.drawText(`AI CONTENT: ${report.aiScore}%`, { x: MARGIN, y, size: 9, font: boldFont, color: rgb(37 / 255, 99 / 255, 235 / 255) });
  y -= 10;
  cover.drawLine({ start: { x: MARGIN, y }, end: { x: pageWidth - MARGIN, y }, thickness: 0.3, color: LIGHT_GRAY });
  y -= 16;

  // PRIMARY SOURCES
  cover.drawText("PRIMARY SOURCES", { x: MARGIN, y, size: 9, font: boldFont, color: RED });
  y -= 14;

  for (let si = 0; si < Math.min(report.sources.length, 20); si++) {
    const src = report.sources[si];
    if (y < 80) {
      addBrandFooter(cover, font);
      // We'd need a new page but keep it simple for cover
      break;
    }

    const tc = TURNITIN_PDF_COLORS[si % TURNITIN_PDF_COLORS.length];

    // Colored badge
    cover.drawRectangle({ x: MARGIN, y: y - 2, width: 12, height: 12, color: tc });
    cover.drawText(`${si + 1}`, { x: MARGIN + (si + 1 >= 10 ? 2 : 4), y: y + 1, size: 8, font: boldFont, color: WHITE });

    // Source title
    const titleText = src.title.substring(0, 55);
    cover.drawText(titleText, { x: MARGIN + 16, y: y + 4, size: 9, font: boldFont, color: tc });

    // Type
    const typeLabel = src.type === 'web' ? 'Internet Source' : src.type === 'journal' ? 'Journal' : src.type === 'publication' ? 'Publication' : 'Repository';
    cover.drawText(typeLabel, { x: MARGIN + 16, y: y - 5, size: 6.5, font, color: MEDIUM_GRAY });

    // Percentage
    const pctText = src.percentContribution < 1 ? '<1%' : `${src.percentContribution}%`;
    cover.drawText(pctText, { x: pageWidth - MARGIN - 30, y: y + 2, size: 14, font, color: MEDIUM_GRAY });

    y -= 22;
  }

  // Metadata
  y -= 8;
  cover.drawText(`Submission: ${new Date(report.submissionDate).toLocaleString()}   |   ID: ${report.submissionId.substring(0, 13)}`, { x: MARGIN, y, size: 6.5, font, color: MEDIUM_GRAY });
  y -= 8;
  cover.drawText(`File: ${report.fileName || report.title}   |   Words: ${report.wordCount}   |   Chars: ${report.charCount}`, { x: MARGIN, y, size: 6.5, font, color: MEDIUM_GRAY });

  addBrandFooter(cover, font);

  // ═══════ DOCUMENT PAGES ═══════
  // Try to embed original PDF pages directly (preserves formatting)
  const originalPDFBytes = await tryGetOriginalPDF(report);

  if (originalPDFBytes) {
    // === ORIGINAL PDF MODE: Preserve document exactly, add watermark overlays ===
    try {
      const originalDoc = await PDFDocument.load(originalPDFBytes);
      const originalPages = await reportDoc.copyPages(originalDoc, originalDoc.getPageIndices());

      // Re-embed fonts and logo for overlay pages
      const overlayFont = font;
      const overlayBoldFont = boldFont;

      for (let i = 0; i < originalPages.length; i++) {
        const page = reportDoc.addPage(originalPages[i]);
        const { width, height } = page.getSize();

        // Add subtle Shantrix watermark header (non-destructive)
        page.drawRectangle({ x: 0, y: height - 18, width, height: 18, color: rgb(1, 1, 1), opacity: 0.85 });
        page.drawRectangle({ x: 0, y: height - 3, width, height: 3, color: BRAND_GREEN, opacity: 0.7 });

        if (logoImage) {
          try { page.drawImage(logoImage, { x: 8, y: height - 16, width: 10, height: 10, opacity: 0.6 }); } catch {}
        }
        page.drawText("Shantrix Report", { x: 22, y: height - 14, size: 7, font: overlayBoldFont, color: BRAND_GREEN, opacity: 0.7 });
        page.drawText(`Page ${i + 1} of ${originalPages.length}`, { x: width - 70, y: height - 14, size: 6, font: overlayFont, color: MEDIUM_GRAY, opacity: 0.7 });

        // Footer bar
        page.drawRectangle({ x: 0, y: 0, width, height: 6, color: BRAND_GREEN, opacity: 0.5 });
      }
    } catch (e) {
      console.error('Failed to embed original PDF, falling back to text rendering:', e);
      renderTextPages(reportDoc, report, font, boldFont, logoImage, pageWidth, pageHeight, contentWidth);
    }
  } else {
    // === TEXT MODE: Render extracted text with highlights ===
    renderTextPages(reportDoc, report, font, boldFont, logoImage, pageWidth, pageHeight, contentWidth);
  }

  // ═══════ SOURCES APPENDIX ═══════
  let appendixPage = reportDoc.addPage([pageWidth, pageHeight]);
  const totalPages = reportDoc.getPageCount();
  addBrandHeader(appendixPage, font, boldFont, totalPages, logoImage, reportDoc);
  let ay = pageHeight - 65;

  appendixPage.drawText("Sources", { x: MARGIN, y: ay, size: 16, font: boldFont, color: BRAND_DARK });
  ay -= 20;

  for (let si = 0; si < report.sources.length; si++) {
    const src = report.sources[si];
    if (ay < 80) {
      addBrandFooter(appendixPage, font);
      appendixPage = reportDoc.addPage([pageWidth, pageHeight]);
      addBrandHeader(appendixPage, font, boldFont, reportDoc.getPageCount(), logoImage, reportDoc);
      ay = pageHeight - 65;
    }

    const tc = TURNITIN_PDF_COLORS[si % TURNITIN_PDF_COLORS.length];

    appendixPage.drawRectangle({ x: MARGIN, y: ay - 2, width: 10, height: 10, color: tc });
    appendixPage.drawText(`${si + 1}`, { x: MARGIN + (si + 1 >= 10 ? 2 : 3.5), y: ay + 1, size: 7, font: boldFont, color: WHITE });

    appendixPage.drawText(src.title.substring(0, 65), { x: MARGIN + 14, y: ay + 3, size: 8.5, font: boldFont, color: tc });

    const typeLabel = src.type === 'web' ? 'Internet Source' : src.type === 'journal' ? 'Journal' : src.type === 'publication' ? 'Publication' : 'Repository';
    appendixPage.drawText(`${typeLabel} · ${src.percentContribution}% · ${src.matchedWords} words · ${src.occurrences} matches`, {
      x: MARGIN + 14, y: ay - 7, size: 6.5, font, color: MEDIUM_GRAY
    });

    if (src.url) {
      appendixPage.drawText(src.url.substring(0, 80), { x: MARGIN + 14, y: ay - 15, size: 6, font, color: rgb(37 / 255, 99 / 255, 235 / 255) });
      ay -= 28;
    } else {
      ay -= 22;
    }
  }

  if (report.sources.length === 0) {
    appendixPage.drawText("No external sources were matched.", { x: MARGIN, y: ay, size: 9, font, color: MEDIUM_GRAY });
  }

  // Summary
  ay -= 16;
  appendixPage.drawLine({ start: { x: MARGIN, y: ay }, end: { x: pageWidth - MARGIN, y: ay }, thickness: 0.3, color: LIGHT_GRAY });
  ay -= 14;
  appendixPage.drawText(`Total Sources: ${report.totalSources}     Total Matches: ${report.totalMatches}     Similarity: ${report.similarityScore}%     AI: ${report.aiScore}%`, {
    x: MARGIN, y: ay, size: 8, font: boldFont, color: BRAND_DARK
  });

  addBrandFooter(appendixPage, font);

  // Save
  const pdfBytes = await reportDoc.save();
  const blob = new Blob([pdfBytes as unknown as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `shantrix-report-${report.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Renders text content with highlights (fallback when original PDF is not available)
 */
function renderTextPages(
  reportDoc: PDFDocument,
  report: GeneratedReport,
  font: PDFFont,
  boldFont: PDFFont,
  logoImage: any,
  pageWidth: number,
  pageHeight: number,
  contentWidth: number
) {
  const highlightMap = buildHighlightMap(report);
  const lines = report.content.split("\n");

  let page = reportDoc.addPage([pageWidth, pageHeight]);
  let pageNum = reportDoc.getPageCount();
  addBrandHeader(page, font, boldFont, pageNum, logoImage, reportDoc);
  let y = pageHeight - 65;

  // Legend
  page.drawText("Document Analysis", { x: MARGIN, y, size: 14, font: boldFont, color: BRAND_DARK });
  y -= 14;
  page.drawRectangle({ x: MARGIN, y: y - 2, width: 30, height: 8, color: PLAG_HIGHLIGHT });
  page.drawText("= Plagiarism", { x: MARGIN + 34, y, size: 7, font, color: MEDIUM_GRAY });
  page.drawRectangle({ x: MARGIN + 100, y: y - 2, width: 30, height: 8, color: AI_HIGHLIGHT });
  page.drawText("= AI Content", { x: MARGIN + 134, y, size: 7, font, color: MEDIUM_GRAY });
  y -= 16;

  let globalCharOffset = 0;

  for (const line of lines) {
    if (line.trim() === "") {
      globalCharOffset += line.length + 1;
      y -= 6;
      continue;
    }

    // Wrap long lines
    const words = line.split(/\s+/);
    let currentLine = "";
    const wrappedLines: string[] = [];

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const testWidth = font.widthOfTextAtSize(testLine, FONT_SIZE);
      if (testWidth > contentWidth - 15 && currentLine) {
        wrappedLines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    if (currentLine) wrappedLines.push(currentLine);

    let lineCharCursor = globalCharOffset;

    for (const wLine of wrappedLines) {
      if (y < 40) {
        addBrandFooter(page, font);
        page = reportDoc.addPage([pageWidth, pageHeight]);
        pageNum = reportDoc.getPageCount();
        addBrandHeader(page, font, boldFont, pageNum, logoImage, reportDoc);
        y = pageHeight - 65;
      }

      const segStart = lineCharCursor;
      const segEnd = lineCharCursor + wLine.length;

      let hasPlag = false;
      let hasAI = false;
      let sourceIdx = -1;

      for (let ci = segStart; ci < segEnd && ci < report.content.length; ci++) {
        const h = highlightMap.get(ci);
        if (h) {
          if (h.type === "plagiarism") { hasPlag = true; if (sourceIdx < 0) sourceIdx = h.sourceIdx; }
          if (h.type === "ai_generated") hasAI = true;
        }
      }

      const textW = font.widthOfTextAtSize(wLine, FONT_SIZE);

      if (hasPlag) {
        page.drawRectangle({ x: MARGIN, y: y - 3, width: Math.min(textW + 4, contentWidth), height: LINE_HEIGHT, color: PLAG_HIGHLIGHT });
      } else if (hasAI) {
        page.drawRectangle({ x: MARGIN, y: y - 3, width: Math.min(textW + 4, contentWidth), height: LINE_HEIGHT, color: AI_HIGHLIGHT });
      }

      page.drawText(wLine, { x: MARGIN + 1, y, size: FONT_SIZE, font: hasPlag || hasAI ? boldFont : font, color: rgb(0.12, 0.12, 0.12) });

      // Source badge
      if (hasPlag && sourceIdx >= 0) {
        const badgeX = Math.min(MARGIN + textW + 5, pageWidth - MARGIN - 12);
        const tc = TURNITIN_PDF_COLORS[sourceIdx % TURNITIN_PDF_COLORS.length];
        page.drawRectangle({ x: badgeX, y: y - 2, width: 8, height: 8, color: tc });
        page.drawText(`${sourceIdx + 1}`, { x: badgeX + (sourceIdx + 1 >= 10 ? 1 : 2.5), y: y, size: 6, font: boldFont, color: WHITE });
      }

      y -= LINE_HEIGHT;
      lineCharCursor = segEnd;
    }

    globalCharOffset += line.length + 1;
  }

  addBrandFooter(page, font);
}
