import jsPDF from "jspdf";
import { GeneratedReport, MatchSpan, SOURCE_COLORS, AI_HIGHLIGHT } from "@/types/report";

const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const MARGIN_TOP = 40;
const MARGIN_BOTTOM = 30;
const LINE_HEIGHT = 6;
const FONT_SIZE = 10;
const HEADER_HEIGHT = 25;

// Shantrix brand green
const BRAND_GREEN: [number, number, number] = [16, 185, 129];
const BRAND_DARK: [number, number, number] = [15, 23, 42];

function addLogo(doc: jsPDF) {
  const pageWidth = doc.internal.pageSize.getWidth();
  // Green accent bar
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, pageWidth, 4, "F");

  // Logo text
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_GREEN);
  doc.text("Shantrix", MARGIN_LEFT, 15);

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("AI-Powered Academic Integrity Platform", MARGIN_LEFT + 30, 15);

  // Page number
  const pageNum = (doc as any).internal.getCurrentPageInfo().pageNumber;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum}`, pageWidth - MARGIN_RIGHT, 15, { align: "right" });

  // Separator line
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_LEFT, 19, pageWidth - MARGIN_RIGHT, 19);
}

function addFooter(doc: jsPDF) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by Shantrix · ${new Date().toLocaleString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.5);
  doc.line(0, pageHeight - 3, pageWidth, pageHeight - 3);
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - MARGIN_BOTTOM) {
    addFooter(doc);
    doc.addPage();
    addLogo(doc);
    return MARGIN_TOP;
  }
  return y;
}

// Build a map of character offsets to match types
function buildHighlightMap(
  report: GeneratedReport
): Map<number, { type: "plagiarism" | "ai_generated"; sourceTitle: string; similarity: number }> {
  const map = new Map();
  for (const span of report.matchSpans) {
    for (let i = span.startOffset; i < span.endOffset; i++) {
      map.set(i, {
        type: span.matchType,
        sourceTitle: span.sourceTitle,
        similarity: span.similarityScoreForSpan,
      });
    }
  }
  return map;
}

export function exportReportPDF(report: GeneratedReport) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;

  addLogo(doc);
  let y = MARGIN_TOP;

  // ── Title Page ──
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Similarity Report", MARGIN_LEFT, y);
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(report.title, MARGIN_LEFT, y);
  y += 12;

  // Scores boxes
  const boxW = contentWidth / 2 - 5;

  // Similarity box
  doc.setFillColor(254, 243, 199); // yellow-100
  doc.roundedRect(MARGIN_LEFT, y, boxW, 22, 3, 3, "F");
  doc.setFontSize(9);
  doc.setTextColor(120, 53, 15);
  doc.text("Similarity Score", MARGIN_LEFT + 5, y + 7);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`${report.similarityScore}%`, MARGIN_LEFT + 5, y + 18);

  // AI box
  doc.setFillColor(219, 234, 254); // blue-100
  doc.roundedRect(MARGIN_LEFT + boxW + 10, y, boxW, 22, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 64, 175);
  doc.text("AI-Generated Score", MARGIN_LEFT + boxW + 15, y + 7);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`${report.aiScore}%`, MARGIN_LEFT + boxW + 15, y + 18);
  y += 30;

  // Meta info
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const meta = [
    `File: ${report.fileName || report.title}`,
    `Date: ${new Date(report.submissionDate).toLocaleDateString()}`,
    `Words: ${report.wordCount.toLocaleString()} · Characters: ${report.charCount.toLocaleString()} · Pages: ${report.totalPages}`,
    `Matches: ${report.totalMatches} · Sources: ${report.totalSources}`,
    `Submission ID: ${report.submissionId}`,
  ];
  for (const line of meta) {
    doc.text(line, MARGIN_LEFT, y);
    y += 5;
  }
  y += 5;

  // ── Sources Section ──
  y = ensureSpace(doc, y, 15);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Matched Sources", MARGIN_LEFT, y);
  y += 8;

  for (const src of report.sources) {
    y = ensureSpace(doc, y, 14);
    const colorIdx = src.colorIndex % 10;
    const colors: [number, number, number][] = [
      [252, 165, 165], [253, 186, 116], [252, 211, 77], [253, 224, 71], [190, 242, 100],
      [94, 234, 212], [103, 232, 249], [196, 181, 253], [249, 168, 212], [253, 164, 175],
    ];
    doc.setFillColor(...colors[colorIdx]);
    doc.rect(MARGIN_LEFT, y - 3, 3, 10, "F");

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`${src.title}`, MARGIN_LEFT + 6, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `${src.type} · ${src.percentContribution}% · ${src.matchedWords} words · ${src.occurrences} occurrences`,
      MARGIN_LEFT + 6,
      y + 5
    );
    if (src.url) {
      doc.setTextColor(37, 99, 235);
      doc.text(src.url.substring(0, 80), MARGIN_LEFT + 6, y + 9);
    }
    y += 14;
  }

  // ── Legend ──
  y = ensureSpace(doc, y, 15);
  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Highlight Legend:", MARGIN_LEFT, y);
  y += 5;

  doc.setFillColor(254, 240, 138); // yellow highlight for plagiarism
  doc.rect(MARGIN_LEFT, y - 3, 20, 5, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("= Plagiarism Match", MARGIN_LEFT + 22, y);

  doc.setFillColor(191, 219, 254); // blue highlight for AI
  doc.rect(MARGIN_LEFT + 70, y - 3, 20, 5, "F");
  doc.text("= AI-Generated Content", MARGIN_LEFT + 92, y);
  y += 10;

  // ── Line-by-Line Document Analysis ──
  addFooter(doc);
  doc.addPage();
  addLogo(doc);
  y = MARGIN_TOP;

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_DARK);
  doc.text("Line-by-Line Document Analysis", MARGIN_LEFT, y);
  y += 10;

  const highlightMap = buildHighlightMap(report);
  const lines = report.content.split("\n");
  let charOffset = 0;

  doc.setFontSize(FONT_SIZE);

  for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
    const line = lines[lineIdx];
    if (line.trim() === "") {
      charOffset += line.length + 1;
      y += 3;
      continue;
    }

    // Word-wrap the line
    doc.setFont("helvetica", "normal");
    const wrappedLines = doc.splitTextToSize(line, contentWidth - 10);

    for (const wrappedLine of wrappedLines) {
      y = ensureSpace(doc, y, LINE_HEIGHT + 2);

      // Check if any character in this segment is highlighted
      const lineStart = charOffset;
      const lineEnd = charOffset + wrappedLine.length;

      // Find highlights in this wrapped segment
      let hasPlagiarism = false;
      let hasAI = false;
      let matchInfo = "";

      for (let ci = lineStart; ci < lineEnd && ci < report.content.length; ci++) {
        const h = highlightMap.get(ci);
        if (h) {
          if (h.type === "plagiarism") {
            hasPlagiarism = true;
            if (!matchInfo) matchInfo = `[${h.sourceTitle} · ${h.similarity}%]`;
          }
          if (h.type === "ai_generated") hasAI = true;
        }
      }

      // Draw highlight background
      const textWidth = doc.getTextWidth(wrappedLine);
      if (hasPlagiarism) {
        doc.setFillColor(254, 240, 138); // yellow
        doc.rect(MARGIN_LEFT, y - 4, Math.min(textWidth + 4, contentWidth), LINE_HEIGHT, "F");
      } else if (hasAI) {
        doc.setFillColor(191, 219, 254); // blue
        doc.rect(MARGIN_LEFT, y - 4, Math.min(textWidth + 4, contentWidth), LINE_HEIGHT, "F");
      }

      // Draw text
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", hasPlagiarism || hasAI ? "bold" : "normal");
      doc.text(wrappedLine, MARGIN_LEFT + 1, y);

      // Annotation for matched source
      if (hasPlagiarism && matchInfo) {
        doc.setFontSize(5);
        doc.setTextColor(180, 83, 9);
        const annotX = Math.min(MARGIN_LEFT + textWidth + 6, pageWidth - MARGIN_RIGHT - 30);
        doc.text(matchInfo, annotX, y);
        doc.setFontSize(FONT_SIZE);
      }

      y += LINE_HEIGHT;
      charOffset = lineEnd;
    }

    // Account for the newline character
    charOffset = charOffset + 1; // newline
    // Recalculate charOffset properly: after processing wrapped lines, 
    // the actual charOffset should be at the end of the original line + 1 (newline)
    charOffset = lines.slice(0, lineIdx + 1).join("\n").length + 1;
  }

  // ── Final page footer ──
  addFooter(doc);

  // Save
  const fileName = `shantrix-report-${report.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(fileName);
}
