import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import ServiceCard from "@/components/ServiceCard";
import { 
  FileSearch, 
  FileText, 
  Layers, 
  Lightbulb, 
  Mic, 
  Wand2 
} from "lucide-react";
import heroImage from "@/assets/hero-academic.jpg";

export default function Landing() {
  const services = [
    {
      icon: FileSearch,
      title: "Originality Checker",
      description: "AI-powered plagiarism detection for documents. Upload DOCX, PDF, or TXT files and get detailed similarity reports instantly.",
      gradient: "bg-accent",
      link: "/dashboard",
    },
    {
      icon: FileText,
      title: "AI Summarizer",
      description: "Summarize PDFs, books, YouTube videos, and research papers with advanced AI. Save time on lengthy content.",
      gradient: "bg-gradient-to-br from-blue-500 to-cyan-500",
    },
    {
      icon: Layers,
      title: "Flashcard Maker",
      description: "Generate study flashcards automatically from documents, PDFs, or videos. Perfect for exam preparation.",
      gradient: "bg-gradient-to-br from-purple-500 to-pink-500",
    },
    {
      icon: Lightbulb,
      title: "Research Topic Finder",
      description: "Discover unique, unpublished research topics generated by AI. Stand out with original ideas.",
      gradient: "bg-highlight",
      link: "/research-topics",
    },
    {
      icon: Mic,
      title: "AI Podcast Maker",
      description: "Transform video content into engaging podcast audio. Perfect for learning on the go.",
      gradient: "bg-gradient-to-br from-green-500 to-emerald-500",
    },
    {
      icon: Wand2,
      title: "AI Paraphraser & Humanizer",
      description: "Reword text naturally while retaining meaning. Make AI-generated content sound more human.",
      gradient: "bg-gradient-to-br from-orange-500 to-red-500",
      link: "/paraphraser",
    },
  ];

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-accent/5" />
        <div className="container mx-auto px-4 py-20 md:py-32 relative z-10">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h1 className="text-4xl md:text-6xl font-bold mb-6 leading-tight">
                Academic Integrity & AI Tools in{" "}
                <span className="bg-gradient-primary bg-clip-text text-transparent">
                  One Platform
                </span>
              </h1>
              <p className="text-lg text-muted-foreground mb-8 leading-relaxed">
                Upload, check, summarize, paraphrase, and discover unique research 
                with AI-powered tools designed for academic excellence.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link to="/signup">
                  <Button size="lg" className="bg-accent hover:bg-accent/90 text-lg px-8">
                    Start Free
                  </Button>
                </Link>
                <Link to="/pricing">
                  <Button size="lg" variant="outline" className="text-lg px-8 border-2">
                    Upgrade to Pro
                  </Button>
                </Link>
              </div>
            </div>
            
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-primary blur-3xl opacity-20" />
              <img 
                src={heroImage} 
                alt="Academic AI Platform" 
                className="relative z-10 rounded-2xl shadow-elevated"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-20 bg-secondary/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold mb-4">
              Powerful AI Tools for Academics
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Everything you need to excel in your academic journey, powered by cutting-edge AI technology
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {services.map((service, index) => (
              service.link ? (
                <Link to={service.link} key={index}>
                  <ServiceCard {...service} />
                </Link>
              ) : (
                <ServiceCard key={index} {...service} />
              )
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-primary opacity-5" />
        <div className="container mx-auto px-4 text-center relative z-10">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Ready to Transform Your Academic Work?
          </h2>
          <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
            Join thousands of students and educators using Shantrix for academic excellence
          </p>
          <Link to="/signup">
            <Button size="lg" className="bg-highlight hover:bg-highlight/90 text-lg px-12">
              Get Started Today
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8 mt-auto">
        <div className="container mx-auto px-4">
          <div className="flex flex-wrap justify-center gap-6 text-sm text-muted-foreground">
            <a href="#" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-foreground transition-colors">Terms of Service</a>
            <a href="#" className="hover:text-foreground transition-colors">Contact</a>
            <a href="#" className="hover:text-foreground transition-colors">Academic Discounts</a>
          </div>
          <p className="text-center text-sm text-muted-foreground mt-4">
            © 2025 Shantrix. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
