import { useState, useEffect } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { FileCheck, Download, Share2, ArrowLeft, Globe, BookOpen, FileText, Bot } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export default function ReportView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [selectedMatch, setSelectedMatch] = useState<string | null>(null);
  const [report, setReport] = useState<any>(null);
  const [submission, setSubmission] = useState<any>(null);
  const [matches, setMatches] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadReport();
  }, [id]);

  const loadReport = async () => {
    try {
      // Find submission by ID
      const { data: submissionData, error: subError } = await supabase
        .from('submissions')
        .select('*')
        .eq('id', id)
        .single();

      if (subError) throw subError;
      setSubmission(submissionData);

      // Get report for this submission
      const { data: reportData, error: repError } = await supabase
        .from('reports')
        .select('*')
        .eq('submission_id', id)
        .single();

      if (repError) throw repError;
      setReport(reportData);

      // Get matches for this report
      const { data: matchesData, error: matchError } = await supabase
        .from('matches')
        .select('*')
        .eq('report_id', reportData.id)
        .order('similarity_percentage', { ascending: false });

      if (matchError) throw matchError;
      setMatches(matchesData || []);

    } catch (error: any) {
      console.error('Error loading report:', error);
      toast.error('Failed to load report');
      navigate('/dashboard');
    } finally {
      setIsLoading(false);
    }
  };

  const downloadReport = () => {
    if (!submission || !report) return;

    const wordCount = submission.content.split(/\s+/).length;
    const charCount = submission.content.length;
    const plagiarismPercent = 100 - report.originality_score - report.ai_score;

    const reportText = `
═══════════════════════════════════════════════════════
                SHANTRIX SIMILARITY REPORT
═══════════════════════════════════════════════════════

SUBMISSION DETAILS
----------------------------------------------------------
Document Title:      ${submission.title}
Submission Date:     ${new Date(submission.created_at).toLocaleString()}
Submission ID:       ${submission.id}
${submission.file_name ? `File Name:           ${submission.file_name}` : ''}

DOCUMENT STATISTICS
----------------------------------------------------------
Word Count:          ${wordCount}
Character Count:     ${charCount}

ANALYSIS RESULTS
----------------------------------------------------------
Originality Score:   ${report.originality_score}%
AI-Generated:        ${report.ai_score}%
Plagiarism:          ${plagiarismPercent}%
Total Matches:       ${report.total_matches}

MATCHED SOURCES
----------------------------------------------------------
${matches.map((match, idx) => `
${idx + 1}. ${match.source_name}
   Match Type:       ${match.match_type === 'ai_generated' ? 'AI Generated Content' : 'Plagiarism'}
   Similarity:       ${match.similarity_percentage}%
   Matched Text:     "${match.matched_text}"
   ${match.source_url ? `Source URL:       ${match.source_url}` : ''}
`).join('\n')}

FULL DOCUMENT TEXT
═══════════════════════════════════════════════════════
${submission.content}

═══════════════════════════════════════════════════════
Report Generated by Shantrix - AI-Powered Academic Integrity Platform
Generated on: ${new Date().toLocaleString()}
═══════════════════════════════════════════════════════
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `shantrix-report-${submission.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return "text-green-600";
    if (score >= 70) return "text-yellow-600";
    return "text-red-600";
  };

  const getSourceIcon = (type: string) => {
    switch (type) {
      case "journal":
        return <BookOpen className="h-4 w-4" />;
      case "web":
        return <Globe className="h-4 w-4" />;
      case "ai_detector":
        return <Bot className="h-4 w-4" />;
      case "student":
        return <FileText className="h-4 w-4" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  const getMatchColor = (matchType: string) => {
    return matchType === "ai_generated" 
      ? "bg-blue-200 dark:bg-blue-900/40 border-b-2 border-blue-400" 
      : "bg-yellow-200 dark:bg-yellow-900/40 border-b-2 border-yellow-400";
  };

  const renderHighlightedContent = () => {
    if (!submission) return null;
    
    let content = submission.content;
    
    // If no matches, return the full content
    if (matches.length === 0) {
      return <div className="whitespace-pre-wrap leading-relaxed">{content}</div>;
    }
    
    const parts: JSX.Element[] = [];
    let lastIndex = 0;

    // Sort matches by start position
    const sortedMatches = [...matches].sort((a, b) => a.start_position - b.start_position);

    sortedMatches.forEach((match, idx) => {
      // Add text before match
      if (match.start_position > lastIndex) {
        const textBefore = content.substring(lastIndex, match.start_position);
        parts.push(
          <span key={`text-${idx}`} className="leading-relaxed">
            {textBefore}
          </span>
        );
      }

      // Add highlighted match
      const isSelected = selectedMatch === match.id;
      const colorClass = getMatchColor(match.match_type);
      const matchText = content.substring(match.start_position, match.end_position);
      
      parts.push(
        <mark
          key={`match-${idx}`}
          className={`${colorClass} ${isSelected ? 'ring-2 ring-accent shadow-lg' : ''} px-1 rounded cursor-pointer transition-all font-medium`}
          onClick={() => setSelectedMatch(match.id)}
          title={`${match.match_type === 'ai_generated' ? 'AI Generated' : 'Plagiarism'} - ${match.similarity_percentage}% match with ${match.source_name}`}
        >
          {matchText}
        </mark>
      );

      lastIndex = match.end_position;
    });

    // Add remaining text
    if (lastIndex < content.length) {
      parts.push(
        <span key="text-end" className="leading-relaxed">
          {content.substring(lastIndex)}
        </span>
      );
    }

    return <div className="whitespace-pre-wrap leading-relaxed">{parts}</div>;
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-secondary/30">
        <p className="text-muted-foreground">Loading report...</p>
      </div>
    );
  }

  if (!report || !submission) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-secondary/30">
        <p className="text-muted-foreground">Report not found</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-secondary/30">
      {/* Navbar */}
      <nav className="border-b bg-background sticky top-0 z-50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="sm">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Dashboard
              </Button>
            </Link>
            <div className="flex items-center gap-2 font-bold text-xl">
              <FileCheck className="h-6 w-6 text-accent" />
              <span className="bg-gradient-primary bg-clip-text text-transparent">
                Shantrix Similarity Report
              </span>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={downloadReport}>
              <Download className="mr-2 h-4 w-4" />
              Download Report
            </Button>
            <Button variant="outline" size="sm" onClick={() => toast.info('Share feature coming soon!')}>
              <Share2 className="mr-2 h-4 w-4" />
              Share
            </Button>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-6">
        {/* Submission Info Card */}
        <Card className="mb-6 shadow-elevated">
          <CardContent className="pt-6">
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h2 className="text-2xl font-bold mb-4">{submission.title}</h2>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Submission date:</span>
                    <span className="font-medium">{new Date(submission.created_at).toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Submission ID:</span>
                    <span className="font-mono text-xs">{submission.id.substring(0, 13)}</span>
                  </div>
                  {submission.file_name && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">File name:</span>
                      <span className="font-medium">{submission.file_name}</span>
                    </div>
                  )}
                </div>
              </div>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Word count:</span>
                  <span className="font-medium">{submission.content.split(/\s+/).length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Character count:</span>
                  <span className="font-medium">{submission.content.length}</span>
                </div>
                <Separator className="my-3" />
                <div className="flex justify-between items-center">
                  <span className="text-muted-foreground">Originality Score:</span>
                  <span className={`text-2xl font-bold ${getScoreColor(report.originality_score)}`}>
                    {report.originality_score}%
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-muted-foreground">AI-Generated:</span>
                  <span className="text-2xl font-bold text-blue-600">{report.ai_score}%</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid lg:grid-cols-4 gap-6">
          {/* Document Viewer (Main Panel - Takes 3 columns) */}
          <Card className="lg:col-span-3 shadow-elevated">
            <CardHeader className="border-b">
              <div className="flex justify-between items-start">
                <div>
                  <CardTitle className="text-xl mb-2">Full Document Text</CardTitle>
                  <div className="flex gap-6 text-sm text-muted-foreground">
                    <div className="flex items-center gap-2">
                      <div className="w-4 h-4 bg-yellow-100 dark:bg-yellow-900/30 border border-yellow-300 rounded"></div>
                      <span>Plagiarism Match</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-4 h-4 bg-blue-100 dark:bg-blue-900/30 border border-blue-300 rounded"></div>
                      <span>AI Generated</span>
                    </div>
                  </div>
                </div>
                <Badge variant="outline" className="text-lg px-4 py-2">
                  Page 1
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <ScrollArea className="h-[800px]">
                <div className="p-12 bg-white dark:bg-gray-900">
                  <div className="max-w-none prose prose-sm dark:prose-invert" style={{ 
                    fontSize: '14px', 
                    lineHeight: '1.8',
                    fontFamily: 'Georgia, serif'
                  }}>
                    {renderHighlightedContent()}
                  </div>
                </div>
              </ScrollArea>
            </CardContent>
          </Card>

          {/* Sidebar - Sources Summary */}
          <div className="space-y-4">
            {/* Quick Stats */}
            <Card className="shadow-elevated border-2 border-accent/20">
              <CardHeader className="pb-3">
                <CardTitle className="text-base">Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <div className="p-3 bg-green-50 dark:bg-green-900/20 rounded-lg text-center">
                  <div className={`text-3xl font-bold ${getScoreColor(report.originality_score)}`}>
                    {report.originality_score}%
                  </div>
                  <p className="text-xs text-muted-foreground mt-1">Original</p>
                </div>
                
                <Separator />
                
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Plagiarism:</span>
                    <span className="font-semibold text-yellow-600">{100 - report.originality_score - report.ai_score}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">AI Content:</span>
                    <span className="font-semibold text-blue-600">{report.ai_score}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Matches:</span>
                    <span className="font-semibold">{report.total_matches}</span>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Sources List */}
            <Card className="shadow-elevated">
              <CardHeader className="pb-3">
                <CardTitle className="text-base">Sources ({matches.length})</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[600px]">
                  <div className="px-4 pb-4 space-y-2">
                    {matches.length === 0 ? (
                      <p className="text-xs text-muted-foreground text-center py-8">
                        No matches detected
                      </p>
                    ) : (
                      matches.map((match, idx) => (
                        <div
                          key={match.id}
                          className={`p-3 rounded-lg border-2 cursor-pointer transition-all ${
                            selectedMatch === match.id
                              ? "border-accent bg-accent/5"
                              : "border-transparent hover:border-accent/30 hover:bg-secondary/50"
                          }`}
                          onClick={() => setSelectedMatch(match.id)}
                        >
                          <div className="flex items-start gap-2 mb-2">
                            <div className="flex-shrink-0 w-6 h-6 rounded-full bg-accent/10 flex items-center justify-center text-xs font-bold">
                              {idx + 1}
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 mb-1">
                                {getSourceIcon(match.source_type)}
                                <span className={`text-xs font-bold ${match.match_type === "ai_generated" ? "text-blue-600" : "text-yellow-600"}`}>
                                  {match.similarity_percentage}%
                                </span>
                              </div>
                              <p className="text-xs font-medium truncate">{match.source_name}</p>
                              <p className="text-xs text-muted-foreground line-clamp-2 mt-1">
                                {match.matched_text.substring(0, 80)}...
                              </p>
                            </div>
                          </div>
                          {match.source_url && (
                            <a
                              href={match.source_url}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-xs text-accent hover:underline"
                              onClick={(e) => e.stopPropagation()}
                            >
                              View source →
                            </a>
                          )}
                        </div>
                      ))
                    )}
                  </div>
                </ScrollArea>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}